import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import 'animate.css';
import "./custom.scss";
//  import "../../public/css/color10.css";
import { headers } from 'next/headers'
// import "./globals.css";
import BootstrapClient from "@/app/component/bootstrap-client";
import { AuthProvider } from "@/context/AuthContext";
import Header from "./component/Header";
import Footer from "./component/Footer";
import Script from "next/script";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const headersList = await headers();
  const path = headersList.get('x-pathname');
  //  path.startsWith(['/about-us','/contact-us','doctor-profile','/doctors','/forgot-password','/register','/user-dashboard','/verify-otp','/login'])


  return (

    <>
      {!path?.startsWith(['/admin']) ? <html lang="en">
        <head>
          <link href="/css/frontend.css" rel="stylesheet" type="text/css" />
          <link href="/css/color10.css" rel="stylesheet" type="text/css" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <AuthProvider>
            <main className="mainSec">
              <Header />

              <main className="middleSec">{children}</main>

              <Footer />
            </main>
          </AuthProvider>
        </body>
        <BootstrapClient />
      </html> :

        <html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-theme="default" data-theme-colors="default" data-sidebar-visibility="show" data-layout-style="default" data-bs-theme="light" data-layout-width="fluid" data-layout-position="fixed" data-body-image="none">

          <head>
            <meta charSet="utf-8" />
            <title>Journals | Mind</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
            <meta content="Themesbrand" name="author" />
            <link rel="stylesheet" href="/assets/libs/gridjs/theme/mermaid.min.css" />
            {/* App favicon */}
            <link rel="shortcut icon" href="/assets/images/favicon.ico" />
            {/* aos css */}
            <link rel="stylesheet" href="/assets/libs/aos/aos.css" />
            {/* Layout config Js */}
            {/* Bootstrap Css */}
            <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            {/* Icons Css */}
            <link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
            {/* App Css*/}
            <link href="/assets/css/app.min.css" rel="stylesheet" type="text/css" />
            {/* custom Css*/}
            <link href="/assets/css/custom.min.css" rel="stylesheet" type="text/css" />
          </head>


          <body data-aos-easing="ease-out-back" data-aos-duration="1000" data-aos-delay="0"
            className="">


            {children}

            <Script src="/assets/libs/bootstrap/js/bootstrap.bundle.min.js" />
            <Script src="/assets/libs/simplebar/simplebar.min.js" />
            <Script src="/assets/libs/node-waves/waves.min.js" />
            <Script src="/assets/libs/feather-icons/feather.min.js" />
            <Script src="/assets/js/pages/plugins/lord-icon-2.1.0.js" />
            <Script src="/assets/js/plugins.js" />
            <Script src="/assets/js/app.js" />
            <Script src="/assets/js/pages/listjs.init.js" />
            <Script src="/assets/libs/prismjs/prism.js" />
            <Script src="/assets/js/layout.js" />
            <Script src="/assets/libs/swiper/swiper-bundle.min.js" />
            <Script src="/assets/js/pages/landing.init.js" />
            <Script src="/assets/libs/list.js/list.min.js" />
            <Script src="/assets/libs/list.pagination.js/list.pagination.min.js" />
            <Script src="/assets/js/pages/invoiceslist.init.js" />
            <Script src="/assets/libs/sweetalert2/sweetalert2.min.js" />
            <Script src="/assets/js/pages/invoicedetails.js" />
            <Script src="/assets/libs/aos/aos.js" />
            <Script src="/assets/js/pages/animation-aos.init.js" />
            <Script src="/assets/libs/particles.js/particles.js" />
            <Script src="/assets/js/pages/particles.app.js" />






          </body>

        </html>

      }
    </>
  );
}
